default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true
  extract_css: false
  static_assets_extensions:
    - .html
    - .erb
    - .haml
    - .slim
    - .md
    - .json
    - .map
    - .svg
    - .eot
    - .ttf
    - .woff
    - .woff2
    - .png
    - .jpg
    - .jpeg
    - .gif

development:
  <<: *default
  compile: true

  # Verifies that versions and hashed value of the package contents in the project's package.json
  # are up to date. You can disable this feature by uncommenting the line below.
  # check_yarn_integrity: false

  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    pretty: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'

test:
  <<: *default
  compile: true

  # Verifies that versions and hashed value of the package contents in the project's package.json
  # are up to date. You can disable this feature by uncommenting the line below.
  # check_yarn_integrity: false

production:
  <<: *default
  compile: false

  # Verifies that versions and hashed value of the package contents in the project's package.json
  # are up to date. You can disable this feature by uncommenting the line below.
  # check_yarn_integrity: false

  # Extract and emit a css file
  extract_css: true

  static_assets_extensions:
    - .html
    - .erb
    - .haml
    - .slim
    - .md
    - .json
    - .map
    - .svg
    - .eot
    - .ttf
    - .woff
    - .woff2
    - .png
    - .jpg
    - .jpeg
    - .gif